// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rickywei/sparrow/project/api"
	"github.com/rickywei/sparrow/project/handler"
)

// Injectors from wire.go:

func WireApp() (*App, error) {
	userHandler := handler.NewUserHandler()
	apiAPI := api.NewApi(userHandler)
	app, err := NewApp(apiAPI)
	if err != nil {
		return nil, err
	}
	return app, nil
}
